### PR TITLE
Changes to be compatible with WebEssentials 2015

### PR DESCRIPTION
**Pull request by raboud**
this fix is related to issue #13

### CODE REVIEW

**Comment by styfle** [comment]
@raboud Thanks for doing this!

**Comment by styfle** [comment]
Note: "compatile" should probably be "compatible"

**Comment by raboud** [comment]
I have two more pull requests but I must have mucked something up since they both also show these changes.....so I did not make them.

I guess I need to wait till this is committed.

**Comment by madskristensen** [comment]
Thanks, this is great

**Pull request merged**
