### PR TITLE
Vs2022 compatibility

### PR DESCRIPTION
**Pull request by vborioni-onit**
Hi,
upgrading the package Microsoft.VisualStudio.SDK from 16.x to 17.x made this work on vs 2022.

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks, but now it won't work on VS 2019

**Comment by vborioni-onit** [comment]
Ouch I feared so :D What's the plan ? Make a different package for vs2020 ?

**Comment by chrisjshields** [comment]
Any update on this?

**Comment by madskristensen** [comment]
Not yet, but I'm planning on adding support

**Comment by madskristensen** [comment]
I can't take the PR as is

**Comment by vborioni-onit** [comment]
I understand, can you share the plan you have in mind ? Can we help with that ? We are a little bit stuck here :D

**Comment by valeriob** [comment]
Hi @madskristensen gentle ping, how can we help to provide a version for vs 2022 ?
Thanks

**Comment by madskristensen** [comment]
At this point, I believe the only valid solution is to drop VS 2019 support and upload a VS 2022 compatible one under a new ID on the Marketplace.

**Comment by madskristensen** [comment]
I'm uploading _TypeScript Definition Generator 2022_ right this moment. It will be ready for download and testing in 5 minutes

**Pull request closed without merging**
