### PR TITLE
Use camelCase for baseName 

### PR DESCRIPTION
**Pull request by mbreaton**
fixes issue around subclassed names not being generated in camel case in typescript definition files

### CODE REVIEW

**Comment by madskristensen** [comment]
This would break existing users, right? Perhaps this should be an option?

**Comment by mbreaton** [comment]
No, as far as I can tell, it fixes what is currently broken. The generated code uses camel case for class definitions, but not for the class name used when extending. The CamelCaseClassName (which uses DtsPackage.Options.CamelCaseTypeNames option) addresses this. See issue [#24](https://github.com/madskristensen/TypeScriptDefinitionGenerator/issues/24)

**Comment by madskristensen** [comment]
Thanks

**Comment by mbreaton** [comment]
No, thank ***you*** for your exhaustive work - I cannot begin to tell you how much your simple tools have made my life easier.

**Pull request merged**
